version: "3.7"

services:
  fastapi-app:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "5001:5001"
    networks:
      - loadtest-net

  jmeter:
    build:
      context: ./jmeter
      dockerfile: Dockerfile
    container_name: jmeter
    volumes:
      - ./jmeter:/jmeter
    command:
      - jmeter
      - -n
      - -t5001

      - /jmeter/fastapi_test_plan.jmx
      - -l
      - /jmeter/results.jtl
      - -JBASE_URL=http://fastapi-app:5001
      - -Jjmeter.save.saveservice.output_format=csv
      - -e
      - -o
      - /jmeter/report
    networks:
      - loadtest-net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - loadtest-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - loadtest-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loadtest-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - loadtest-net

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password # 원하는 비밀번호로 변경
      - DOCKER_INFLUXDB_INIT_ORG=my-org # 원하는 조직 이름으로 변경
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket # 원하는 버킷 이름으로 변경
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token # 강력한 토큰으로 변경
    networks:
      - loadtest-net


networks:
  loadtest-net:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  grafana-data:
  influxdb_data:
